// Build-time module for pro-shell.
//
// Three build-time jobs:
//
//   1. Publish the static nav manifest (`shared/manifest.ts`) as
//      `#pro-shell/manifest`, to the app AND the Nitro graph, the way
//      nuxtseo.com's pro-features module does. Identity, route, group and
//      order are manifest facts; the sidebar derives, it does not declare.
//   2. Give every `/pro/dashboard/**` page the dashboard layout, so a feature
//      layer never has to remember the shell.
//   3. Collect `proTab` page meta into `#pro-shell/tabs.mjs`.
//
// Everything else (state resolvers, chrome components) is registered at
// runtime via the `pro:feature` hook from each layer's
// `app/plugins/pro-feature.ts`. See ADR-0015 (modernized).
//
// Each pro-* layer plugin looks like:
//
//   import { useGscFeatureDataState } from '../composables/...'
//   import ProGscFeatureChrome from '../internal/components/...'
//
//   export default defineNuxtPlugin({
//     name: 'pro-gsc:feature',
//     setup(nuxtApp) {
//       nuxtApp.hook('pro:feature', (registry) => {
//         registry.add({
//           id: 'search-console',
//           ...
//           stateResolver: siteId => useGscFeatureDataState(siteId, { includeStale: true }),
//         })
//         registry.addChrome({
//           forFeatures: ['search-console', 'indexing', 'analysis'],
//           component: ProGscFeatureChrome,
//         })
//       })
//     },
//   })

import type { ProSiteFeatureTab } from '../shared/types'
import { addComponent, addImportsDir, addTemplate, createResolver, defineNuxtModule } from 'nuxt/kit'
import { proSiteFeatureNavOrder } from '../shared/manifest'

/** Every page under this prefix renders inside the dashboard shell. */
const DASHBOARD_PREFIX = '/pro/dashboard'
const DASHBOARD_LAYOUT = 'pro-dashboard'

export default defineNuxtModule({
  meta: {
    name: 'pro-shell',
    configKey: 'proShell',
  },
  setup(_options, nuxt) {
    const resolver = createResolver(import.meta.url)
    const manifestSource = resolver.resolve('../shared/manifest.ts')

    // Force eager page-meta scan so `pages:extend` sees `proTab` from
    // definePageMeta. Default is 'after-resolve' which fires too late.
    nuxt.options.experimental ||= {} as never
    const experimental = nuxt.options.experimental as Record<string, unknown>
    experimental.scanPageMeta = true
    // `layout` is not one of Nuxt's default extraction keys, so without this a
    // page that declares its own layout looks layout-less to the hook below and
    // gets the dashboard shell it did not ask for. Declared here rather than in
    // the layer's nuxt.config because a layer's `experimental` block does not
    // survive the merge with the root config.
    const extractionKeys = (experimental.extraPageMetaExtractionKeys as string[] | undefined) ?? []
    experimental.extraPageMetaExtractionKeys = Array.from(new Set([...extractionKeys, 'proTab', 'pro', 'layout']))

    const tabsByFeature = new Map<string, ProSiteFeatureTab[]>()

    nuxt.hook('pages:extend', (pages) => {
      tabsByFeature.clear()
      const join = (parent: string, child: string) => {
        if (!child)
          return parent
        if (child.startsWith('/'))
          return child
        return `${parent.replace(/\/$/, '')}/${child}`
      }
      const walk = (list: typeof pages, parentPath: string) => {
        for (const page of list) {
          const absPath = join(parentPath, page.path ?? '')
          const meta = (page.meta ?? {}) as { proTab?: Omit<ProSiteFeatureTab, 'to'> }
          if (meta.proTab) {
            const tab: ProSiteFeatureTab = {
              feature: meta.proTab.feature,
              label: meta.proTab.label,
              icon: meta.proTab.icon,
              order: meta.proTab.order ?? 100,
              to: absPath,
            }
            const list = tabsByFeature.get(tab.feature) ?? []
            list.push(tab)
            tabsByFeature.set(tab.feature, list)
          }
          // Every dashboard page renders in the shell. Assigning it here keeps
          // the feature layers out of it: a page that does declare a layout
          // (the focused account shell) keeps the one it declared.
          if (absPath.startsWith(DASHBOARD_PREFIX)) {
            page.meta ||= {}
            page.meta.layout ??= DASHBOARD_LAYOUT
          }
          if (page.children?.length)
            walk(page.children, absPath)
        }
      }
      walk(pages, '')
      for (const list of tabsByFeature.values())
        list.sort((a, b) => a.order - b.order)
    })

    // The static nav manifest reaches BOTH the app and the Nitro graph through
    // one virtual, so a server handler and the sidebar resolve the same row.
    addTemplate({
      filename: 'pro-shell/manifest.mjs',
      write: true,
      getContents: () => [
        `// Auto-generated by pro-shell. Do not edit.`,
        `export * from ${JSON.stringify(manifestSource)}`,
      ].join('\n'),
    })

    addTemplate({
      filename: 'pro-shell/manifest.d.ts',
      write: true,
      getContents: () => `export * from '${manifestSource.replace(/\.ts$/, '')}'`,
    })

    addTemplate({
      filename: 'pro-shell/tabs.mjs',
      write: true,
      getContents: () => {
        const obj = Object.fromEntries(tabsByFeature)
        return [
          `// Auto-generated by pro-shell. Do not edit.`,
          `export const tabsByFeature = ${JSON.stringify(obj, null, 2)}`,
          `export const topNavOrder = ${JSON.stringify(proSiteFeatureNavOrder)}`,
        ].join('\n')
      },
    })

    addTemplate({
      filename: 'pro-shell/tabs.d.ts',
      write: true,
      getContents: () => [
        `import type { ProSiteFeatureTab } from '${resolver.resolve('../shared/types')}'`,
        `export declare const tabsByFeature: Record<string, ProSiteFeatureTab[]>`,
        `export declare const topNavOrder: string[]`,
      ].join('\n'),
    })

    nuxt.options.alias['#pro-shell/manifest'] = resolver.resolve(nuxt.options.buildDir, 'pro-shell/manifest.mjs')
    nuxt.options.alias['#pro-shell/tabs'] = resolver.resolve(nuxt.options.buildDir, 'pro-shell/tabs.mjs')

    addImportsDir(resolver.resolve('../app/composables'))
    addComponent({
      name: 'ProSiteFeaturePage',
      filePath: resolver.resolve('../app/components/pro-shell/ProSiteFeaturePage.vue'),
    })
    addComponent({
      name: 'ProSurfacePlaceholder',
      filePath: resolver.resolve('../app/components/pro-shell/ProSurfacePlaceholder.vue'),
    })
  },
})
