// Build-time module for pro-shell.
//
// Its only build-time job is collecting `proTab` metadata from page meta
// and emitting `#pro-shell/tabs.mjs` — a `featureId → ProSiteFeatureTab[]`
// map. Everything else (feature definitions, state resolvers, chrome
// components) is registered at runtime via the `pro:feature` hook from
// each layer's `app/plugins/pro-feature.ts`. See ADR-0015 (modernized).
//
// Each pro-* layer plugin looks like:
//
//   import { useGscFeatureDataState } from '../composables/...'
//   import ProGscFeatureChrome from '../internal/components/...'
//
//   export default defineNuxtPlugin({
//     name: 'pro-gsc:feature',
//     setup(nuxtApp) {
//       nuxtApp.hook('pro:feature', (registry) => {
//         registry.add({
//           id: 'search-console',
//           ...
//           stateResolver: siteId => useGscFeatureDataState(siteId, { includeStale: true }),
//         })
//         registry.addChrome({
//           forFeatures: ['search-console', 'indexing', 'analysis'],
//           component: ProGscFeatureChrome,
//         })
//       })
//     },
//   })

import type { ProSiteFeatureTab } from '../shared/types'
import { addComponent, addImportsDir, addTemplate, createResolver, defineNuxtModule } from 'nuxt/kit'

export interface ProShellOptions {
  /** Top-nav display order. Features not listed fall through alphabetically. */
  topNavOrder?: string[]
}

export default defineNuxtModule<ProShellOptions>({
  meta: {
    name: 'pro-shell',
    configKey: 'proShell',
  },
  defaults: {
    topNavOrder: [
      'search-console',
      'indexing',
      'cwv',
      'lighthouse',
      'analysis',
      'competitors',
      'keywords',
      'chat',
    ],
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)

    // Force eager page-meta scan so `pages:extend` sees `proTab` from
    // definePageMeta. Default is 'after-resolve' which fires too late.
    nuxt.options.experimental ||= {} as never
    ;(nuxt.options.experimental as Record<string, unknown>).scanPageMeta = true

    const tabsByFeature = new Map<string, ProSiteFeatureTab[]>()

    nuxt.hook('pages:extend', (pages) => {
      tabsByFeature.clear()
      const join = (parent: string, child: string) => {
        if (!child)
          return parent
        if (child.startsWith('/'))
          return child
        return `${parent.replace(/\/$/, '')}/${child}`
      }
      const walk = (list: typeof pages, parentPath: string) => {
        for (const page of list) {
          const absPath = join(parentPath, page.path ?? '')
          const meta = (page.meta ?? {}) as { proTab?: Omit<ProSiteFeatureTab, 'to'> }
          if (meta.proTab) {
            const tab: ProSiteFeatureTab = {
              feature: meta.proTab.feature,
              label: meta.proTab.label,
              icon: meta.proTab.icon,
              order: meta.proTab.order ?? 100,
              to: absPath,
            }
            const list = tabsByFeature.get(tab.feature) ?? []
            list.push(tab)
            tabsByFeature.set(tab.feature, list)
          }
          if (page.children?.length)
            walk(page.children, absPath)
        }
      }
      walk(pages, '')
      for (const list of tabsByFeature.values())
        list.sort((a, b) => a.order - b.order)
    })

    addTemplate({
      filename: 'pro-shell/tabs.mjs',
      write: true,
      getContents: () => {
        const obj = Object.fromEntries(tabsByFeature)
        return [
          `// Auto-generated by pro-shell. Do not edit.`,
          `export const tabsByFeature = ${JSON.stringify(obj, null, 2)}`,
          `export const topNavOrder = ${JSON.stringify(options.topNavOrder)}`,
        ].join('\n')
      },
    })

    addTemplate({
      filename: 'pro-shell/tabs.d.ts',
      write: true,
      getContents: () => [
        `import type { ProSiteFeatureTab } from '${resolver.resolve('../shared/types')}'`,
        `export declare const tabsByFeature: Record<string, ProSiteFeatureTab[]>`,
        `export declare const topNavOrder: string[]`,
      ].join('\n'),
    })

    nuxt.options.alias['#pro-shell/tabs'] = resolver.resolve(nuxt.options.buildDir, 'pro-shell/tabs.mjs')

    addImportsDir(resolver.resolve('../app/composables'))
    addComponent({
      name: 'ProSiteFeaturePage',
      filePath: resolver.resolve('../app/components/pro-shell/ProSiteFeaturePage.vue'),
    })
  },
})
