import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { addTemplate, defineNuxtModule, useLogger, useNuxt } from 'nuxt/kit'

/**
 * Per-layer drizzle schema aggregation, ported from nuxtseo.com's
 * `modules/drizzle-layers`.
 *
 * It walks every Nuxt layer for `server/database/<name>/schema.ts`, emits one
 * aggregated barrel per database into the build directory, and mounts it at
 * `#schema/<name>`, with a `#db/<name>` helper beside it. That alias contract
 * is the point: nuxtseo.com server code imports `#schema/pro` and `#db/pro`,
 * so it transfers here without a rewrite at every import.
 *
 * Two deliberate differences from nuxtseo.com's copy:
 *
 * - The schema itself is still one file (`layers/core/server/db/schema.ts`).
 *   The per-layer file re-exports it, so the barrel has one source today and
 *   room for more later.
 * - `#db/<name>` delegates to this app's own `useDrizzle`. nuxtseo.com's
 *   version builds its own D1 request session; adopting that runtime as well
 *   would give this app two database seams at once.
 */
export interface DatabaseOptions {
  /** Where each layer may place its slice. Default: `server/database/<name>/schema.ts` */
  schemaPath?: string
  /** Where the `useDb` helper comes from. */
  dbFrom: string
}

export interface ModuleOptions {
  /** Per-db config keyed by db name. Each name `n` mounts `#schema/<n>` and `#db/<n>`. */
  databases: Record<string, DatabaseOptions>
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'drizzle-layers',
    configKey: 'drizzleLayers',
  },
  defaults: { databases: {} },
  setup(options) {
    const nuxt = useNuxt()
    const logger = useLogger('drizzle-layers')

    nuxt.options.nitro ||= {}
    nuxt.options.nitro.alias ||= {}
    // The emitted barrel re-exports `.ts` sources by absolute path. Nitro
    // externalises build-dir files in dev and loads them through native ESM,
    // which cannot resolve a `.ts`. Inlining keeps them on the bundler path.
    nuxt.options.nitro.externals ||= {}
    nuxt.options.nitro.externals.inline ||= []
    nuxt.options.nitro.externals.inline.push(resolve(nuxt.options.buildDir, 'drizzle-layers'))

    const aliasPaths: Record<string, string> = {}
    const flushers: Array<() => void> = []

    function discover(relPath: string): string[] {
      const found = new Set<string>()
      for (const layer of nuxt.options._layers) {
        const p = resolve(layer.config.rootDir, relPath)
        if (existsSync(p))
          found.add(p)
      }
      return [...found].sort()
    }

    function renderSchema(sources: string[], name: string): string {
      if (!sources.length)
        logger.warn(`[${name}] no schema files found`)
      const body = sources.map(src => `export * from '${src.replace(/\.ts$/, '')}'`).join('\n')
      return `// Generated by modules/drizzle-layers. Do not edit.\n${body}\n`
    }

    function renderDb(name: string, dbFrom: string, schemaDst: string): string {
      return [
        '// Generated by modules/drizzle-layers. Do not edit.',
        `export * as schema from '${schemaDst.replace(/\.ts$/, '')}'`,
        `export { useDrizzle as useDb } from '${dbFrom.replace(/\.ts$/, '')}'`,
        '',
      ].join('\n')
    }

    for (const [name, dbOpts] of Object.entries(options.databases)) {
      const schemaRel = dbOpts.schemaPath ?? `server/database/${name}/schema.ts`
      const dbFrom = resolve(nuxt.options.rootDir, dbOpts.dbFrom)

      const schemaTpl = addTemplate({
        filename: `drizzle-layers/${name}/schema.ts`,
        write: true,
        getContents: () => renderSchema(discover(schemaRel), name),
      })

      const dbTpl = addTemplate({
        filename: `drizzle-layers/${name}/db.ts`,
        write: true,
        getContents: () => renderDb(name, dbFrom, schemaTpl.dst),
      })

      // `addTemplate({ write: true })` only flushes during the debounced
      // `builder:generateApp` cycle, and Nitro can resolve the alias first.
      // Write the same content here so the file is never momentarily absent.
      flushers.push(() => {
        for (const [dst, content] of [
          [schemaTpl.dst, renderSchema(discover(schemaRel), name)],
          [dbTpl.dst, renderDb(name, dbFrom, schemaTpl.dst)],
        ] as Array<[string, string]>) {
          if (existsSync(dst) && readFileSync(dst, 'utf8') === content)
            continue
          mkdirSync(dirname(dst), { recursive: true })
          writeFileSync(dst, content)
        }
      })

      for (const [alias, dst] of [[`#schema/${name}`, schemaTpl.dst], [`#db/${name}`, dbTpl.dst]] as Array<[string, string]>) {
        nuxt.options.alias[alias] = dst
        nuxt.options.nitro.alias[alias] = dst
        aliasPaths[alias] = dst
      }

      logger.info(`#schema/${name} → ${relative(nuxt.options.rootDir, schemaTpl.dst)}`)
    }

    const flush = () => {
      for (const f of flushers) f()
    }
    flush()

    nuxt.hook('prepare:types', ({ tsConfig }) => {
      tsConfig.compilerOptions ||= {}
      tsConfig.compilerOptions.paths ||= {}
      for (const [alias, dst] of Object.entries(aliasPaths))
        tsConfig.compilerOptions.paths[alias] = [dst]
    })

    nuxt.hook('builder:watch', (event, path) => {
      if (event === 'add' || event === 'unlink' || path.includes('server/database/')) {
        flush()
        nuxt.callHook('builder:generateApp')
      }
    })
  },
})
